name: Labwork 1 check
on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]
  workflow_dispatch:
jobs:  
  build:
    name: XML verification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install -g fast-xml-parser
      - name: Validate X3D
        run: xml2js -V *.html
